apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
